# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# This action checks that required kernel configs have not been removed or
# modified to an undesirable value. It also checks that new configs added to
# the kernel config files are in the list of required configs.
name: Kernel Required Configs Check

on:
  push:
    branches: [main, dev, 1.0*, 2.0*]
  pull_request:
    branches: [main, dev, 1.0*, 2.0*]

jobs:
  check:
    name: Kernel configs check
    runs-on: ubuntu-latest

    steps:
      # Checkout the branch of our repo that triggered this action
      - name: Workflow trigger checkout
        uses: actions/checkout@v2
        
      - name: Get base commit for PRs
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git fetch origin ${{ github.base_ref }}
          echo "base_sha=$(git rev-parse origin/${{ github.base_ref }})" >> $GITHUB_ENV
          echo "Merging ${{ github.sha }} into ${{ github.base_ref }}"

      - name: Get base commit for Pushes
        if: ${{ github.event_name == 'push' }}
        run: |
          git fetch origin ${{ github.event.before }}
          echo "base_sha=${{ github.event.before }}" >> $GITHUB_ENV
          echo "Merging ${{ github.sha }} into ${{ github.event.before }}"


      # For consistency, we use the same major/minor version of Python that CBL-Mariner ships
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Get Python dependencies
        run: python3 -m pip install -r toolkit/scripts/requirements.txt

      # Check kernel configs
      - name: Check if config files changed
        run: |
          echo "Files changed: '$(git diff-tree --no-commit-id --name-only -r ${{ env.base_sha }} ${{ github.sha }})'"
          changed_configs=$(git diff-tree --diff-filter=d  --no-commit-id --name-only -r ${{ env.base_sha }} ${{ github.sha }} | { grep "SPECS/kernel/config.*$" || test $? = 1; })
          echo "Files to validate: '${changed_configs}'"
          echo "updated-configs=$(echo ${changed_configs})" >> $GITHUB_ENV

      - name: Parse for new config changes
        run: |
          # Check for new configs in the PR
          # and check if they are in required configs
          if [[ -n ${{ env.updated-configs}} ]]; then
            for word in "${{ env.updated-configs}}"; do
              config_diff=$(git diff-tree -p -r ${{ env.base_sha }} ${{ github.sha }} -- ${word})
              echo "config_diff for ${word} : ${config_diff}"
              python3 .github/workflows/check_new_kernel_configs.py --required_configs=toolkit/scripts/mariner-required-configs.json --config_str="${config_diff}"
            done
          fi

      - name: Run kernel config checking script AMD64
        run: python3 toolkit/scripts/check_required_kernel_configs.py --required_configs toolkit/scripts/mariner-required-configs.json --config_file SPECS/kernel/config
      
      - name: Run kernel config checking script ARM64
        run: python3 toolkit/scripts/check_required_kernel_configs.py --required_configs toolkit/scripts/mariner-required-configs.json --config_file SPECS/kernel/config_aarch64

