name: Check Kernel

on:
  push:
    branches: [main, dev, 1.0*, rlmenge*]
  pull_request:
    branches: [main, dev, 1.0*, rlmenge*]

jobs:
  kernel-check:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch of our repo that triggered this action
      - name: Workflow trigger checkout
        uses: actions/checkout@v2

      - name: Get base commit for PRs
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git fetch origin ${{ github.base_ref }}
          echo "base_sha=$(git rev-parse origin/${{ github.base_ref }})" >> $GITHUB_ENV 
          echo "Merging ${{ github.sha }} into ${{ github.base_ref }}"

      - name: Get the changed files
        run: |
          echo "Files changed: '$(git diff-tree --no-commit-id --name-only -r ${{ env.base_sha }} ${{ github.sha }})'"
          changed_specs=$(git diff-tree --no-commit-id --name-only -r ${{ env.base_sha }} ${{ github.sha }})
          echo "Files to validate: '${changed_specs}'"
          echo "updated-specs=$(echo ${changed_specs})" >> $GITHUB_ENV

      - name: Check for all files
        run: |
          declare -a list_of_kernel_files=("SPECS-SIGNED/kernel-signed/kernel-signed.spec")
          missing_files=""
          for val in "${list_of_kernel_files[@]}"; do
            if [[ ! ${{ env.updated-specs }} == *$val* ]]; then
                missing_files+="$val"
                missing_files+=$'\n'
            fi
          done

          if [ -s linted_specs.diff ]
          then
            echo -e "\n====================== KERNEL CHECK FAILED ======================"
            echo "Missing the following files:"
            echo $missing_files
            exit 1
          fi
          exit 0                    
          