# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# Workflow to automatedly verify the quickstart instructions

name: Verify Quickstart 2.0

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

jobs:
  get_input-srpms:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2
      with:
        ref: '2.0-stable'

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Install Remaining Prerequisites
      run: |
        # Golang and docker are already installed on the agent
        sudo apt-get update
        sudo apt -y install make tar wget curl rpm qemu-utils genisoimage python-minimal bison gawk parted
        sudo apt -y install pigz

  iso_quickstart:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2
      with:
        ref: '2.0-stable'

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Install Remaining Prerequisites
      run: |
        # Golang and docker are already installed on the agent
        sudo apt-get update
        sudo apt -y install make tar wget curl rpm qemu-utils genisoimage python-minimal bison gawk parted
        sudo apt -y install pigz

    - name: ISO Quick Start
      run: |
        pushd toolkit
        sudo make iso REBUILD_TOOLS=y REBUILD_PACKAGES=n
        popd

  vhdx_quickstart:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2
      with:
        ref: '2.0-stable'

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Install Remaining Prerequisites
      run: |
        # Golang and docker are already installed on the agent
        sudo apt-get update
        sudo apt -y install make tar wget curl rpm qemu-utils genisoimage python-minimal bison gawk parted
        sudo apt -y install pigz

    - name: VHDX Quick Start
      run: |
        pushd toolkit
        sudo make image REBUILD_TOOLS=y REBUILD_PACKAGES=n
        popd
